### ISSUE TITLE
你好，請問一下我在本機都可以正常運作，但丟到虛擬主機上，就會失敗

### ISSUE THREAD

**Issue by derekypp** [6chinwei/LINE-Pay-PHP-Tutorial#1]
你好，請問一下我在本機都可以正常運作，但丟到虛擬主機上，就會失敗，使用 linepay 提交 支付
就會跳回上一層目錄

加上了ini_set('display_errors', 1); 也沒有看到錯誤訊息

**Comment by 6chinwei** [comment]
Hi derekypp, 
請問您說的問題是發生在發送 reserve 請求的頁面嗎？不知道您的頁面流程是怎樣設計的，不過我建議可以先試試以下方法檢查是否是環境的問題：
1. 檢查虛擬主機的 **PHP 版本**、**啟用的 PHP 模組**以及**網頁伺服器版本**（例如 Apache）是否和本機相同
2. 查看虛擬主機上網頁伺服器（例如 Apache）的 Log 記錄有沒有記錄到相關的錯誤訊息
